### ISSUE TITLE
I get an error when I open emacs

### ISSUE THREAD

**Issue by patrixd** [lmartel/emacs-asana#9]
I'm new in emacs.  

I have tried to compile asana.el, but I get the following error:
```
Warning (initialization): An error occurred while loading ‘/Users/patrimun/.emacs.d/init.el’:
Symbol's function definition is void: global-asana-mode
```

Would you please tell me how to install the package? It does not appear in the list of packages and I think I'm doing something wrong.

**Comment by lmartel** [comment]
Thanks for the report! It looks like this is only a warning, so you should be able to ignore it and still use the package without issues. I get lots of those warnings from various packages.

I believe the way to silence that warning is to add an autoload; I'll look into it when I next update the code.

**Comment by patrixd** [comment]
Thank you for answering so quickly!
